<!--footer start-->
<footer class="py-3 py-lg-4 text-center" style="background-image: linear-gradient(to right, rgba(117,117,117,0.9), rgba(117,117,117,0.3))">
    <div class="container">
        <div class="social mb-4">
            <a href="https://www.facebook.com/pages/PIS-Poslovni-Informacioni-Sistemi/419822691493357" target="_blank" class="fa fa-facebook mx-1"></a>
            <a href="http://www.linkedin.com/company/pis---poslovno-informacioni-sistemi-d.o.o." target="_blank" class="fa fa-linkedin mx-1"></a>
			<a href="https://www.Youtube.com" class="fa fa-youtube mx-1"></a>
        </div>
        <p class="copyright mb-0 text-white">Copyright 2019 <a href="http://www.pis.rs" target="_blank" class="footer-color">PIS</a>. All Rights Reserved. </p>
    </div>
</footer><!--footer end-->
