<!--header start-->
<header class="py-3" style="background-image: linear-gradient(to right, rgba(220, 220, 220,0.3), rgba(220, 220, 220,0.9))">
    <div class="container">
        <nav class="navbar navbar-expand-md navbar-light px-0">
        <!--logo start-->
        <div class="navbar-container" id="navbar-container">
            <asp:Image id="logo" runat="server" CssClass="logo-image" imageurl="~/img/logo.jpg"/>
            <asp:Label id="lblscnsnaziv" runat="server" CssClass="scns-name pl-1 pl-sm-4">                               
                Studentski centar Novi Sad                                    
            </asp:Label>         
        </div><!--logo end-->
                    
        </nav>
    </div>
</header><!--header end-->
